repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: name-tests-test
        args: ["--pytest-test-first"]
        # exclude: "^tests/helpers.py"
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: debug-statements
      - id: check-yaml
      - id: check-xml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: check-ast
      - id: check-added-large-files

  # IMPORTANT: Run isort before black, to ensure isort cannot break formatting rules.
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: "7.3.0"
    hooks:
      - id: flake8
        args: ["--max-line-length", "120", "--ignore", "E203"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.18.2"
    hooks:
      - id: mypy
        additional_dependencies: []

  - repo: https://github.com/pycqa/pylint
    rev: "v3.3.8"
    hooks:
      - id: pylint
        args: ["--rcfile", "pylintrc"]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: ["-x"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        files: \.(json|markdown|md|yaml|yml|toml)$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.2.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, ci, chore, test] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
